### ISSUE TITLE
"Report a Vulnerability" link goes to 404 page on GitHub

### ISSUE THREAD

**Issue by jeff-luszcz** [placemark/placemark#15]
Description:

In the page:
https://github.com/placemark/placemark/security

There is a link with the title "Report a Vulnerability"

When clicked on it brings you to a 404 page on Github
https://github.com/placemark/placemark/security/advisories/new

I notice there is no public Green "New Draft Security Advisory" button available as well

I am logged in with my normal Github account

**Comment by tmcw** [comment]
Should be accessible now - apparently GitHub's reporting UI is private by default.

**Comment by jeff-luszcz** [comment]
Perfect, works as expected. Closing issue!
