### ISSUE TITLE
 Error in setup using Docker both in MacOS and Ubuntu

### ISSUE THREAD

**Issue by anup39** [placemark/placemark#26]
Used docker guide to setup the project. Getting  an error. Tried both in Ubuntu and MacOS. Getting the same error as shown in the image. 
<img width="1054" alt="error_installation" src="https://github.com/placemark/placemark/assets/61059165/891c4237-d24f-4436-a688-0a33ff9667e5">

**Comment by tmcw** [comment]
I'll take a look. The Docker files are a recent (and much appreciated!) contribution, while Placemark has in development been developed and deployed without using Docker, instead running on the host machine on macOS and using a blueprint on Render. Hopefully it's possible to support both.

**Comment by tmcw** [comment]
To clarify - do you mean both macOS and Linux hosts for the docker subhost?

The prisma not found error definitely points to prisma not being installed at an earlier step, which probably produced a more precise error. Can you try and provide a more complete error / build report?

**Comment by tmcw** [comment]
This should be fixed in #30, let me know if you still encounter issues!
