### ISSUE TITLE
Update links

### ISSUE THREAD

**Issue by tordans** [placemark/placemark#47]
There are a few links that could be updated

* https://github.com/placemark links to https://www.placemark.io/
* https://www.placemark.io/ links to the broken URL https://www.placemark.io/replay/w/id-d4d6bfd0af15/:null/mp_/https://github.com/placemark/placemark-oss
* https://github.com/placemark/placemark links to https://www.placemark.io/

**Comment by tmcw** [comment]
Thanks, I think all of these are fixed now!
