### ISSUE TITLE
Geometry information not working on play.placemark.io

### ISSUE THREAD

**Issue by reesericci** [placemark/placemark#56]
When trying to access Geometry Information after accessing a line, I get an error stating "please try again". This issue persisted across Firefox, GNOME Web (WebKit), and Chromium.

These are the console errors:

![console showing a next.js useMutation error](https://github.com/placemark/placemark/assets/19589006/e17ad107-4c4a-48af-97bf-8fffebe66bac)

[Screencast from 2024-02-29 14-44-30.webm](https://github.com/placemark/placemark/assets/19589006/2c683a05-17e4-42af-ba74-6a527cd759b4)

**Comment by tmcw** [comment]
Thanks for the bug report! This is some code that would maintain unit preferences in application settings, and those settings are in the database-y part, which I apparently didn't remove well enough.

**Comment by tmcw** [comment]
Fixed in 0bbd441854951893cdac0a59abbb11ed94301d14
