### ISSUE TITLE
Support for RTL text on the map

### ISSUE THREAD

**Issue by galdalali** [placemark/placemark#57]
Hi, 

The tables and JSON files work as expected when using RTL text format (in this case Hebrew), but when displayed on the map, they appear backwards.

<img width="1079" alt="Screenshot 2024-03-10 111902" src="https://github.com/placemark/placemark/assets/8566487/5e9c9734-054f-4d8b-986c-adffd8d897bb">

**Comment by bdon** [comment]
plugin needs to be added in this way: https://docs.mapbox.com/mapbox-gl-js/example/mapbox-gl-rtl-text/

**Comment by tmcw** [comment]
Thanks @bdon for the tip, deploying an update now.
