### ISSUE TITLE
Open GeoJSON from command line / via URL

### ISSUE THREAD

**Issue by tordans** [placemark/placemark#67]
It would be great if there where an option to open a GeoJSON file via URL … which could also be used to create a link that can be opened from command line scripts.

Geojson.io has something that can be used like …

```js
exec(
  `open http://geojson.io/#data=data:application/json,${encodeURIComponent(JSON.stringify(outputGeosjon))}`,
)
```

**Comment by tmcw** [comment]
Yep! I'd love to do this, will try to get the time to work on it soon

**Comment by tmcw** [comment]
Done in #72
