### ISSUE TITLE
Increase max zoom

### ISSUE THREAD

**Issue by rovo89** [placemark/placemark#80]
This is a very nice and helpful tool, thanks! However, for fine-tuning a GeoJSON on centimeter level, the max zoom is way too restrictive. I changed the zoom level in the debugger and something like 25 or even 26 would be required. Any chance you can increase the default?

**Comment by tmcw** [comment]
Sure, solid idea! Fixed in #81, max zoom is now 26.

**Comment by rovo89** [comment]
Thanks! Just tested it and it works very well for my use-case! Had another observation, will open a ticket for that as well.
