### ISSUE TITLE
Support transparency on satellite layer

### ISSUE THREAD

**Issue by lbutler** [placemark/placemark#86]
When using the satellite layer it can be difficult to see the vector data because of the contrast of the satellite image. One simple way to fix this that I use in QGIS is to give the layer transparency which lowers the contrast and improves the visibility of the layer.

You can test how this looks by loading an XYZ layer from mapbox 
`https://api.mapbox.com/styles/v1/mapbox/satellite-v9/tiles/{z}/{x}/{y}?access_token=YOUR_ACCESS_TOKEN
`

I was also able to get this work directly in placemark by modifying the function [`addMapboxStyle`](https://github.com/placemark/placemark/blob/33b42b6011d6bdfe46a4a0b20cfd1e1822416d25/app/lib/layer_config_adapters.ts#L11) in layer_config_adapters.ts to modify the style JSON file if it was the satellite layer and add the following property.

```
paint: {
  "raster-opacity": layer.opacity,
},
```

If you think it is worth adding this functionality, I'm happy to create a PR.

![play placemark io_ (1)](https://github.com/user-attachments/assets/2880c1da-f799-46ec-afad-38dd301390fa)
![play placemark io_](https://github.com/user-attachments/assets/2fb98b95-ce36-4719-9fd2-0ae97bd38b06)

**Comment by tmcw** [comment]
Sure, I'd definitely accept a PR for this change!

**Comment by lbutler** [comment]
Great! I gave it a go and submitted a PR. Its relatively simple but any feedback/change you need, let me know.

**Comment by lbutler** [comment]
Merged with #87
